// <auto-generated />
using System;
using CanteenManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CanteenManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CanteenManagementSystem.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FoodItemId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Category = "Meal",
                            Name = "Burger",
                            Price = 50.0,
                            UserId = 3
                        },
                        new
                        {
                            FoodItemId = 2,
                            Category = "Drink",
                            Name = "Juice",
                            Price = 20.0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            FoodItemId = 1,
                            OrderDateTime = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 1,
                            Status = "Completed",
                            TotalPrice = 50.0,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            FoodItemId = 2,
                            OrderDateTime = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 2,
                            Status = "Preparing",
                            TotalPrice = 20.0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("JonTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            JonTitle = "Chef",
                            Name = "Mohamed Samy",
                            PhoneNumber = "01011112222",
                            Status = "Available",
                            UserId = 3
                        },
                        new
                        {
                            StaffId = 2,
                            JonTitle = "Cashier",
                            Name = "Ali Hassan",
                            PhoneNumber = "01133334444",
                            Status = "Busy",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "ahmed@mail.com",
                            Name = "Ahmed Ali",
                            Password = "ahmed@12345",
                            PhoneNumber = "01012345678",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "sara@mail.com",
                            Name = "Sara Mohamed",
                            Password = "sara@12345",
                            PhoneNumber = "01198765432",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "admin@mail.com",
                            Name = "Admin User Ali",
                            Password = "admin@12345",
                            PhoneNumber = "01099998888",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.FoodItem", b =>
                {
                    b.HasOne("CanteenManagementSystem.Models.User", "User")
                        .WithMany("FoodItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.Order", b =>
                {
                    b.HasOne("CanteenManagementSystem.Models.FoodItem", "FoodItem")
                        .WithMany("Orders")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanteenManagementSystem.Models.Staff", "Staff")
                        .WithMany("Orders")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CanteenManagementSystem.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Staff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.Staff", b =>
                {
                    b.HasOne("CanteenManagementSystem.Models.User", "User")
                        .WithMany("Staffs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.FoodItem", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.Staff", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CanteenManagementSystem.Models.User", b =>
                {
                    b.Navigation("FoodItems");

                    b.Navigation("Orders");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
